# Generated by Django 5.1.4 on 2025-04-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bri', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('height', models.FloatField()),
                ('waist', models.FloatField()),
            ],
        ),
    ]
